name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run API Update
        run: curl --header "secret:${{ secrets.SECRET }}" https://api.stg.casperecosystem.io/api/update

      - name: Run Refresh Gatsby
        run: curl -X POST https://webhook.gatsbyjs.com/hooks/data_source/publish/0331c161-911e-4c3a-944b-${{ secrets.GATSBY_ID }}
